[tool.poetry]
name = "clipper"
version = "0.1.0"
description = ""
authors = ["Gabriel Peter"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
moviepy = "^1.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
